### PR TITLE
Update to babel's new preset-env process

### PR DESCRIPTION
**Pull request by gnarmedia**
Babel has deprecated the older style of preset configuration, so this
is the updated process.

### CODE REVIEW

**Comment by gnarmedia** [comment]
I notice this might not be a perfect commit, let me know if anything can be done to improve it.

**Comment by gingur** [comment]
@gnarmedia or @loganfsmyth this info doesn't seem correct, running `npm run build && nodemon dist/index.js` will not auto rebuild the files built by `npm run build` when executed. Suggest reverting this PR or properly updating to prior `nodemod` config.

**Comment by gnarmedia** [comment]
I'll look into this tonight

**Comment by gingur** [comment]
Just need to change `npm run build && nodemon dist/index.js` to `nodemon --exec babel-node index.js`

**Pull request merged**
